async (page) => {
  const results = [];
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const assert = (condition, label) => { if (!condition) throw new Error(label); results.push(label); };
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto('http://127.0.0.1:5179/');
  await page.waitForFunction(() => window.__pelican?.status.ready, { timeout: 60000 });
  await page.evaluate(() => document.fonts.ready);
  assert(await page.locator('#scene canvas').count() === 1, '3D scene initializes');
  await page.locator('#pause-button').click();
  const pausedDistance = await page.evaluate(() => window.__pelican.status.distance);
  await page.waitForTimeout(600);
  assert(await page.evaluate(() => window.__pelican.status.distance) === pausedDistance, 'Pause freezes distance');
  await page.locator('#speed').evaluate(input => { input.value = '24'; input.dispatchEvent(new Event('input', { bubbles: true })); });
  assert(await page.locator('#speed-output').textContent() === '24', 'Speed slider updates model and UI');
  await page.locator('#ride-button').click();
  await page.waitForTimeout(600);
  assert(await page.evaluate(() => window.__pelican.status.distance) > pausedDistance, 'Ride button resumes movement');
  await page.locator('#weather-button').click();
  assert(await page.evaluate(() => window.__pelican.status.night && document.body.classList.contains('night')), 'Day/night updates scene and page');
  await page.locator('#weather-button').click();
  await page.locator('#sound-button').click();
  await page.waitForFunction(() => window.__pelican.status.sound);
  assert(await page.locator('#sound-button').getAttribute('aria-pressed') === 'true', 'Audio starts only after gesture');
  await page.locator('#sound-button').click();
  await page.waitForFunction(() => !window.__pelican.status.sound);
  assert(true, 'Audio can be muted');
  await page.locator('#bell-button').click();
  assert((await page.locator('#toast').textContent()).includes('叮铃铃'), 'Bell has audible and visual feedback');
  const downloadPromise = page.waitForEvent('download');
  await page.locator('#photo-button').click();
  const download = await downloadPromise;
  await download.saveAs('artifacts/postcard.png');
  assert(download.suggestedFilename() === 'pelican-post-sunshine.png', 'Postcard PNG downloads successfully');
  await page.locator('#nav-story').click();
  assert(await page.locator('#story-dialog').isVisible(), 'Story dialog opens');
  await page.keyboard.press('Escape');
  assert(!(await page.locator('#story-dialog').isVisible()), 'Dialog closes with Escape');
  const cameraBefore = await page.evaluate(() => window.__pelican.status.camera);
  const box = await page.locator('#scene').boundingBox();
  await page.mouse.move(box.x + box.width * .45, box.y + box.height * .6);
  await page.mouse.down();
  await page.mouse.move(box.x + box.width * .64, box.y + box.height * .55, { steps: 15 });
  await page.mouse.up();
  await page.waitForTimeout(300);
  const cameraAfter = await page.evaluate(() => window.__pelican.status.camera);
  assert(Math.abs(cameraBefore[0] - cameraAfter[0]) > .1, 'Dragging orbits the camera');
  await page.mouse.wheel(0, -250);
  await page.waitForTimeout(300);
  assert(await page.evaluate(() => window.__pelican.status.zoom) > 1, 'Wheel zoom works');
  await page.locator('#reset-button').click();
  await page.waitForTimeout(2300);
  assert(Math.abs(await page.evaluate(() => window.__pelican.status.zoom) - 1) < .01, 'Camera resets correctly');
  for (const width of [1440, 1024, 768, 600, 390, 320]) {
    await page.setViewportSize({ width, height: 900 });
    await page.waitForTimeout(100);
    const actualWidth = await page.evaluate(() => document.documentElement.scrollWidth);
    assert(actualWidth <= width, `No horizontal overflow at ${width}px`);
  }
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('#pause-button').click();
  await page.mouse.move(0, 0);
  await page.waitForTimeout(3300);
  await page.screenshot({ path: 'artifacts/mobile-verified.png', fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.screenshot({ path: 'artifacts/desktop-verified.png', fullPage: true });
  await page.locator('#weather-button').click();
  await page.mouse.move(0, 0);
  await page.waitForTimeout(3400);
  await page.screenshot({ path: 'artifacts/night-verified.png', fullPage: true });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.reload();
  await page.waitForFunction(() => window.__pelican?.status.ready, { timeout: 60000 });
  assert(!(await page.evaluate(() => window.__pelican.status.playing)), 'Reduced-motion starts paused');
  await page.waitForTimeout(500);
  assert(await page.evaluate(() => window.__pelican.status.distance) === 0, 'Reduced-motion avoids automatic riding');
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  assert(errors.length === 0, `No uncaught browser errors (${errors.length})`);
  return { passed: results.length, results, errors, status: await page.evaluate(() => window.__pelican.status) };
}
